spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

logging:
  level:
    root: INFO
    com.example: INFO

app:
  cleanup:
    cron: ${CLEANUP_CRON:0 0 2 * * *}     # daily at 2 AM
